### ISSUE TITLE
Dateiname mit ##datim## hängt nach Zeit was an

### ISSUE THREAD

**Issue by zonky2** [terminal42/contao-leads#108]
Export als Excel
Vorgabe für Dateiname: `Umfrage Feedback ##datim##.xls`
Dateiname beim Export: `Umfrage Feedback 25.03.2021 11 14.20211114.xls`
Exportdatum: `25.03.2021 11:14`

**Comment by fritzmg** [comment]
I can't confirm this issue:

| Custom file name | Actual file name |
| --- | --- |
| `foobar_##date##.xslx` | `foobar_2021-03-25.xslx` |
| `foobar_##datim##.xlsx` | `foobar_2021-03-25 11:30.xlsx`<sup>1</sup> |

<sup>1</sup> This actually leads to an error on Windows, since `:` is not allowed in file paths. But that's expected.

@zonky2 what is your `contao.localconfig.datimFormat` setting?

**Comment by zonky2** [comment]
`d.m.Y H:i`

**Comment by fritzmg** [comment]
Couldn't reproduce it with that either - but may be there are platform differences.

**Comment by zonky2** [comment]
When configuring for the first time, I had not yet specified an extension - if this is missing, the number thing is attached under windows.

**Comment by fritzmg** [comment]
In Windows you cannot use `##datim##` with `d.m.Y H:i`. Does the same behavior occur with a different `datim` format or `##date##`?

**Comment by zonky2** [comment]
maybe the tool should append the extension automatically
