### ISSUE TITLE
lead CSV whiteout filetype

### ISSUE THREAD

**Issue by AryaSvitkona** [terminal42/contao-leads#17]
Contao: 3.4.4
leads: latest

After create an export configuration and start an export, leads doesn't add the filetype (CSV) to the filename.
In the same way it doesn't seperate the fields by comma ",".
Have the same bug on multiple installations.

**Comment by Toflar** [comment]
The filename is supposed not to add the extension. Just add it yourself?

**Comment by AryaSvitkona** [comment]
Thanks, I thought it will be added automatically by dropdown.
How do you separate the fields? By comma? I don't think that works well, cause of the commas in a textfield. Or am I wrong?

kindly regards

**Comment by Toflar** [comment]
The CSV spec clearly states how you have to properly escape the code.

```csv
"first row","second row with text,with,commas,that just works","third row"
```

**Comment by marcosimbuerger** [comment]
The cause are the line breaks. contao-leads stores and exports the line breaks from textareas. In the CSV file, line breaks are used as line seperators. Therefore, each line break from the textarea generates a new line in the CSV file and shows you a wrong view (for example in MS Excel).

**Comment by Toflar** [comment]
If line breaks are correctly placed between the two `"`, it's valid CSV. 

The specification in RFC 4180 clearly states this:

> Fields containing line breaks (CRLF), double quotes, and commas
       should be enclosed in double-quotes.  For example:

       "aaa","b CRLF
       bb","ccc" CRLF
       zzz,yyy,xxx

If Excel cannot handle this, then it's an Excel issue.

**Comment by marcosimbuerger** [comment]
Yes, it's an Excel issue... -.-    (See: [stackoverflow#1241220](http://stackoverflow.com/questions/1241220/generating-csv-file-for-excel-how-to-have-a-newline-inside-a-value) )

But... two new fields for selecting your own selectors for the export would be a nice feature ;-)
Like the CSV export options in phpMyAdmin. Because the most users will open the CSV file with MS Excel.

**Comment by aschempp** [comment]
Why not use the excel export for that? And maybe combine it with the template option?

**Comment by Toflar** [comment]
I don't see why you ever want to use that, really. There is one CSV specification and it's plain simple. Why can't people just use commas if the specification says so? Is it that hard? Excel is shit anyway, that's why you can export to Excel 2003 and 2007+ directly, so you don't need the CSV option there :)
