### ISSUE TITLE
Formular ID is shown even if backend user has no permissions

### ISSUE THREAD

**Issue by mpitz** [terminal42/contao-leads#46]
The form ID is shown in the navigation if backend user has no permission for the form:

![image](https://user-images.githubusercontent.com/6831223/29664865-c9c2ef36-88d1-11e7-90ba-fb605f774393.png)

**Comment by mpitz** [comment]
Is there a roadmap for this fix?

**Comment by Toflar** [comment]
Not at the moment but you're welcome to contribute.
https://www.terminal42.ch/en/open-source.html

**Comment by Toflar** [comment]
@qzminski is that fixed with https://github.com/terminal42/contao-leads/commit/a52ef9fcadb08f39575f6f56971d64c08f9abb10?

**Comment by qzminski** [comment]
I don't think so.

**Comment by Toflar** [comment]
Ah, form permissions are checked but I guess you were talking about `ID 3` which is an orphan. There's no form anymore so it cannot check for permissions either. I've changed it so that only admins can see orphan data. Fixed in https://github.com/terminal42/contao-leads/commit/0223df018de55e71f475fcd21f0a834b617f39f1
